# Generated by Django 2.0.6 on 2020-05-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品名称')),
                ('sub_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品副标题')),
                ('pfone', models.CharField(max_length=100, verbose_name='产品特性1')),
                ('pftwo', models.CharField(max_length=100, verbose_name='产品特性2')),
                ('pfthree', models.CharField(max_length=100, verbose_name='产品特性3')),
                ('pffour', models.CharField(max_length=100, verbose_name='产品特性4')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('img1', models.ImageField(upload_to='product', verbose_name='大图片1')),
                ('img2', models.ImageField(upload_to='product', verbose_name='大图片2')),
                ('img3', models.ImageField(upload_to='product', verbose_name='大图片3')),
                ('img4', models.ImageField(upload_to='product', verbose_name='大图片4')),
                ('img5', models.ImageField(upload_to='product', verbose_name='大图片5')),
                ('img6', models.ImageField(upload_to='product', verbose_name='大图片6')),
                ('img7', models.ImageField(upload_to='product', verbose_name='大图片7')),
                ('video_des', models.CharField(max_length=100, verbose_name='视频主描述')),
                ('sub_video_desc', models.CharField(max_length=300, verbose_name='视频副描述')),
                ('video_url', models.FileField(upload_to='video', verbose_name='视频上传路径')),
            ],
            options={
                'db_table': 'product',
                'verbose_name': '产品表',
                'verbose_name_plural': '产品表',
            },
        ),
    ]
