# Generated by Django 2.0.6 on 2020-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img7',
        ),
        migrations.AddField(
            model_name='product',
            name='lb_1',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='轮播图1'),
        ),
        migrations.AddField(
            model_name='product',
            name='lb_2',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='轮播图2'),
        ),
        migrations.AddField(
            model_name='product',
            name='lb_3',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='轮播图3'),
        ),
        migrations.AddField(
            model_name='product',
            name='lb_4',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='轮播图4'),
        ),
        migrations.AddField(
            model_name='product',
            name='lb_5',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='轮播图4'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_img',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='视频背景图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='大图片1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='大图片2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='大图片3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pffour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品特性4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pfone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品特性1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pfthree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品特性3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pftwo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品特性2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_video_desc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='视频副描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_des',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='视频主描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='video', verbose_name='视频上传路径'),
        ),
    ]
