# Generated by Django 2.0.6 on 2020-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200520_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='大图片1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='大图片2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='大图片3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lb_1',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lb_2',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lb_3',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lb_4',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lb_5',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='视频背景图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='imgs/product', verbose_name='视频上传路径'),
        ),
    ]
