# Generated by Django 2.0.6 on 2020-05-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200521_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('lb_1', models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图1')),
                ('lb_2', models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图2')),
                ('lb_3', models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图3')),
                ('lb_4', models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图4')),
                ('lb_5', models.ImageField(blank=True, null=True, upload_to='imgs/product', verbose_name='轮播图4')),
            ],
            options={
                'db_table': 'plb',
                'verbose_name': '产品页轮播图',
                'verbose_name_plural': '产品页轮播图',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='lb_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lb_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lb_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lb_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lb_5',
        ),
        migrations.AddField(
            model_name='productlunbo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
