# Generated by Django 2.0.6 on 2020-05-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200521_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlunbo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product'),
        ),
    ]
