# Generated by Django 2.0.6 on 2020-05-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200521_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlunbo',
            old_name='lb_1',
            new_name='lb',
        ),
        migrations.RemoveField(
            model_name='productlunbo',
            name='lb_2',
        ),
        migrations.RemoveField(
            model_name='productlunbo',
            name='lb_3',
        ),
        migrations.RemoveField(
            model_name='productlunbo',
            name='lb_4',
        ),
        migrations.RemoveField(
            model_name='productlunbo',
            name='lb_5',
        ),
    ]
