# Generated by Django 2.0.6 on 2020-05-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('images', models.ImageField(blank=True, help_text='轮播图', null=True, upload_to='slide', verbose_name='轮播图图片地址')),
                ('name', models.CharField(max_length=20, verbose_name='轮播图名称')),
                ('discrible', models.CharField(max_length=50, verbose_name='轮播图描述')),
                ('banner_url', models.CharField(max_length=30, verbose_name='轮播图广告地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'lbt',
            },
        ),
        migrations.CreateModel(
            name='MoblieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('images', models.ImageField(blank=True, null=True, upload_to='mobile', verbose_name='手机图片地址')),
                ('name', models.CharField(max_length=30, verbose_name='手机图片名称')),
                ('discrible', models.CharField(max_length=150, verbose_name='手机图片描述')),
                ('banner_url', models.CharField(max_length=150, verbose_name='手机广告地址')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'menu',
            },
        ),
    ]
