# Generated by Django 2.0.6 on 2020-05-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleNavHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=20, verbose_name='导航栏标题名称')),
            ],
            options={
                'verbose_name': '中部导航栏标题',
                'db_table': 'mnav',
                'verbose_name_plural': '中部导航栏标题',
            },
        ),
        migrations.CreateModel(
            name='MiddleNavHeaderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('images', models.ImageField(blank=True, null=True, upload_to='nav-img', verbose_name='中部导航栏图片')),
                ('title', models.CharField(max_length=20, verbose_name='中部导航栏标题')),
                ('price', models.IntegerField(verbose_name='中部导航栏价格')),
                ('midhear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MiddleNavHeader', verbose_name='外键关联中部标题')),
            ],
            options={
                'verbose_name': '中部导航栏数据',
                'db_table': 'mnav_data',
                'verbose_name_plural': '中部导航栏数据',
            },
        ),
    ]
