# Generated by Django 2.0.6 on 2020-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_middlenavheader_middlenavheaderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlenavheaderdata',
            name='images_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
