# Generated by Django 2.0.6 on 2020-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_middlenavheaderdata_images_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlenavheaderdata',
            name='images_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
