# Generated by Django 2.0.6 on 2020-05-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_adslist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiddleNavHeaderData',
            new_name='MiddleNavHeaderMobile',
        ),
    ]
