# Generated by Django 2.0.6 on 2020-05-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200518_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlenavheadermobile',
            name='midhear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid_data', to='home.MiddleNavHeader', verbose_name='外键关联中部标题'),
        ),
    ]
