# Generated by Django 2.0.6 on 2020-05-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200519_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftBottomAdsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('images', models.ImageField(blank=True, help_text='广告位上传图片', null=True, upload_to='ads', verbose_name='广告位上传图片')),
                ('images_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '左下部广告表',
                'verbose_name_plural': '左下部广告表',
                'db_table': 'lbads',
            },
        ),
        migrations.CreateModel(
            name='MiddleAdsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('images', models.ImageField(blank=True, help_text='广告位上传图片', null=True, upload_to='ads', verbose_name='广告位上传图片')),
                ('images_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '中部广告表',
                'verbose_name_plural': '中部广告表',
                'db_table': 'midads',
            },
        ),
        migrations.CreateModel(
            name='RightBottomAdsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('images', models.ImageField(blank=True, help_text='广告位上传图片', null=True, upload_to='ads', verbose_name='广告位上传图片')),
                ('images_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '右下部广告表',
                'verbose_name_plural': '右下部广告表',
                'db_table': 'rbads',
            },
        ),
    ]
