# Generated by Django 2.0.6 on 2020-05-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_leftbottomadslist_middleadslist_rightbottomadslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftbottomadslist',
            name='images',
            field=models.ImageField(blank=True, help_text='广告位上传图片', null=True, upload_to='lads', verbose_name='广告位上传图片'),
        ),
        migrations.AlterField(
            model_name='middleadslist',
            name='images',
            field=models.ImageField(blank=True, help_text='广告位上传图片', null=True, upload_to='mads', verbose_name='广告位上传图片'),
        ),
        migrations.AlterField(
            model_name='rightbottomadslist',
            name='images',
            field=models.ImageField(blank=True, help_text='广告位上传图片', null=True, upload_to='rads', verbose_name='广告位上传图片'),
        ),
    ]
