# Generated by Django 2.0.6 on 2020-05-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200519_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightbottomadslist',
            name='discrable',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='rightbottomadslist',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='rightbottomadslist',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标题'),
        ),
    ]
