# Generated by Django 2.0.6 on 2020-05-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200519_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightbottomadslist',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='秒杀颜色选项'),
        ),
        migrations.AddField(
            model_name='rightbottomadslist',
            name='is_new',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='是否是新品'),
        ),
    ]
