# Generated by Django 2.0.6 on 2020-05-19 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200519_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=30, verbose_name='左侧标题')),
            ],
            options={
                'verbose_name': '左侧菜单',
                'verbose_name_plural': '左侧菜单',
                'db_table': 'left_title',
            },
        ),
        migrations.AddField(
            model_name='moblielist',
            name='lmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.LeftMenu'),
        ),
    ]
