# Generated by Django 2.0.6 on 2020-05-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200519_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moblielist',
            name='lmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmenu', to='home.LeftMenu'),
        ),
    ]
