# Generated by Django 2.0.6 on 2020-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200519_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslist',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品id'),
        ),
        migrations.AddField(
            model_name='banner',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品id'),
        ),
        migrations.AddField(
            model_name='leftbottomadslist',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品id'),
        ),
        migrations.AddField(
            model_name='middleadslist',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品id'),
        ),
        migrations.AddField(
            model_name='middlenavheadermobile',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品id'),
        ),
        migrations.AddField(
            model_name='moblielist',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品id'),
        ),
        migrations.AddField(
            model_name='rightbottomadslist',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='产品id'),
        ),
    ]
