# Generated by Django 2.0.6 on 2020-05-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
    ]
